---
asyncapi: 3.0.0
id: 'pionix:de:everest:lifecycle_API'
info:
  title: 'EVerest API definition for lifecycle control'
  version: 1.0.0
  description: >-
    API for EVerest modules and clients to control the modules lifecycle.
    Provides facilities to (re)start and stop modules and monitor their status.
  license:
    name: Apache-2.0
    url: https://opensource.org/licenses/Apache-2.0
  tags:
    - name: EVerest
    - name: Lifecycle
servers:
  default:
    pathname: 'everest_api/1/lifecycle/'
    host: 'localhost:1883'
    description: default local MQTT
    protocol: mqtt
defaultContentType: application/json

channels:
  send_request_stop_modules:
    address: 'm2e/stop_modules'
    messages:
      send_request_stop_modules:
        $ref: '#/components/messages/send_request_stop_modules'
  receive_reply_stop_modules:
    address: null
    messages:
      receive_reply_stop_modules:
        $ref: '#/components/messages/receive_reply_stop_modules'

  send_request_start_modules:
    address: 'm2e/start_modules'
    messages:
      send_request_start_modules:
        $ref: '#/components/messages/send_request_start_modules'
  receive_reply_start_modules:
    address: null
    messages:
      receive_reply_start_modules:
        $ref: '#/components/messages/receive_reply_start_modules'

  send_request_get_everest_version:
    address: 'm2e/get_everest_version'
    messages:
      send_request_get_everest_version:
        $ref: '#/components/messages/send_request_get_everest_version'
  receive_reply_get_everest_version:
    address: null
    messages:
      receive_reply_get_everest_version:
        $ref: '#/components/messages/receive_reply_get_everest_version'

  receive_status:
    address: 'e2m/status'
    messages:
      receive_status:
        $ref: '#/components/messages/receive_status'


operations:
  send_request_stop_modules:
    title: 'Stop modules'
    action: send
    channel:
      $ref: '#/channels/send_request_stop_modules'
    description: 'Request EVerest to stop all currently running modules.'
    reply:
      address:
        location: "$message.header#/replyTo"
      channel:
        $ref: '#/channels/receive_reply_stop_modules'

  receive_reply_stop_modules:
    title: 'Reply to stop_modules request'
    action: receive
    channel:
      $ref: '#/channels/receive_reply_stop_modules'

  send_request_get_everest_version:
    title: 'Request EVerest version'
    action: send
    channel:
      $ref: '#/channels/send_request_get_everest_version'
    description: 'Request EVerest to send its version.'
    reply:
      address:
        location: "$message.header#/replyTo"
      channel:
        $ref: '#/channels/receive_reply_get_everest_version'

  receive_reply_get_everest_version:
    title: 'Reply to get EVerest version request'
    action: receive
    channel:
      $ref: '#/channels/receive_reply_get_everest_version'

  send_request_start_modules:
    title: 'Start modules'
    action: send
    channel:
      $ref: '#/channels/send_request_start_modules'
    description: 'Request EVerest to start modules.'
    reply:
      address:
        location: "$message.header#/replyTo"
      channel:
        $ref: '#/channels/receive_reply_start_modules'

  receive_reply_start_modules:
    title: 'Reply to start_modules request'
    action: receive
    channel:
      $ref: '#/channels/receive_reply_start_modules'

  receive_status:
    title: 'Receive execution status'
    action: receive
    channel:
      $ref: '#/channels/receive_status'
    description: 'Published when EVerest execution status changes.'


components:
  messages:
    send_request_stop_modules:
      name: send_request_stop_modules
      title: 'Stop modules request'
      summary: 'Request EVerest to stop all currently running modules.'
      contentType: application/json
      payload:
        type: object
        properties:
          headers:
            type: object
            properties:
              replyTo:
                type: string
                description: Address to send the response to.
      examples:
        - summary: "Request to stop all modules"
          payload:
            headers:
              replyTo: arbitrary/reply/topic
    receive_reply_stop_modules:
      name: receive_reply_stop_modules
      title: 'Stop modules reply'
      summary: 'Reply indicating the result of stopping modules.'
      contentType: application/json
      payload:
        $ref: '#/components/schemas/StopModulesResult'
      examples:
        - summary: "No modules to stop"
          payload:
            status: "NoModulesToStop"

    send_request_get_everest_version:
      name: send_request_get_everest_version
      title: 'Get EVerest version request'
      summary: 'Request EVerest to send its version.'
      contentType: application/json
      payload:
        type: object
        properties:
          headers:
            type: object
            properties:
              replyTo:
                type: string
                description: Address to send the response to.
      examples:
        - summary: "Request EVerest version"
          payload:
            headers:
              replyTo: arbitrary/reply/topic
    receive_reply_get_everest_version:
      name: receive_reply_get_everest_version
      title: 'EVerest version reply'
      summary: 'Reply to get EVerest version request.'
      contentType: application/json
      payload:
        $ref: '#/components/schemas/EVerestVersion'
      examples:
        - summary: "EVerest Version report"
          payload:
            name: "everest-core"
            version: "2026.02.0"
            git_version: "a1b2c3d4e5f6g7h8i9j0"

    send_request_start_modules:
      name: send_request_start_modules
      title: 'Start modules request'
      summary: 'Request EVerest to start modules.'
      contentType: application/json
      payload:
        type: object
        properties:
          headers:
            type: object
            properties:
              replyTo:
                type: string
                description: Address to send the response to.
      examples:
        - summary: "Request to start modules"
          payload:
            headers:
              replyTo: arbitrary/reply/topic
    receive_reply_start_modules:
      name: receive_reply_start_modules
      title: 'Start modules reply'
      summary: 'Reply indicating the result of starting modules.'
      contentType: application/json
      payload:
        $ref: '#/components/schemas/StartModulesResult'
      examples:
        - summary: "Modules starting"
          payload:
            status: "Starting"

    receive_status:
      name: receive_status
      title: 'Execution status update'
      summary: 'Published when EVerest execution status changes.'
      contentType: application/json
      payload:
        $ref: '#/components/schemas/ExecutionStatusUpdateNotice'
      examples:
        - summary: "Modules stopped, configuration service available"
          payload:
            tstamp: "2026-03-30T17:45:00Z"
            everest_running: true
            module_status: "NotRunning"
            configuration_api_available: "RW"
            lifecycle_api_ro: false
        - summary: "EVerest not running (last will)"
          payload:
            everest_running: false


  schemas:
    StopModulesResultEnum:
      description: |
        Possible results for stop module requests
        - Stopping: Accepted and modules are commanded to stop but haven't done so yet
        - NoModulesToStop: Accepted, but a no-op since there were no modules running
        - Rejected: Rejected, for some reason (e.g. not allowed)
      type: string
      enum:
        - Stopping
        - NoModulesToStop
        - Rejected
    StartModulesResultEnum:
      description: |
        Possible results for start module requests
        - Starting: Accepted and modules are commanded to start but haven't done so yet
        - Restarting: Modules are commanded to stop and will be commanded to start once they have stopped
        - NoConfigToStart: Accepted, but there is not configuration slot marked to boot from
        - Rejected: Rejected, for some reason (e.g. not allowed)
      type: string
      enum:
        - Starting
        - Restarting
        - NoConfigToStart
        - Rejected
    ModuleExecutionStatusEnum:
      description: |
        State of the modules
        - Running: Modules are running
        - NotRunning: Modules are not running
        - Starting: Transitional state Stopped->Running
        - Stopping: Transitional state Running->Stopped
        - RestartTriggered: Indicates immediately if a restart is intended
      type: string
      enum:
        - Running
        - NotRunning
        - Starting
        - Stopping
        - RestartTriggered
    StopModulesResult:
      description: Result when requesting to stop the modules
      type: object
      additionalProperties: true
      properties:
        status:
          $ref: '#/components/schemas/StopModulesResultEnum'
      required:
        - status
    StartModulesResult:
      description: Result when requesting to start the modules
      type: object
      additionalProperties: true
      properties:
        status:
          $ref: '#/components/schemas/StartModulesResultEnum'
      required:
        - status
    ConfigurationApiAvailability:
      description: |
        Availability of the configuration_API
        - N_A: Not available
        - RO: Available, read-only
        - RW: Available, read-write
      type: string
      enum:
        - N_A
        - RO
        - RW
    ExecutionStatusUpdateNotice:
      description: Execution status summary. Will include all the optional fields, if everest_running is true.
      type: object
      additionalProperties: true
      properties:
        tstamp:
          type: string
          format: date-time
          description: Timestamp of the status update in RFC3339 format
        everest_running:
          type: boolean
        module_status:
          $ref: '#/components/schemas/ModuleExecutionStatusEnum'
        configuration_api_available:
          $ref: '#/components/schemas/ConfigurationApiAvailability'
        lifecycle_api_ro:
          type: boolean
          description: Indicates whether the lifecycle_API itself is in read-only mode
      required:
        - everest_running

    EVerestVersion:
      description: Version designators of the running EVerest instance
      type: object
      additionalProperties: true
      required:
        - name
        - version
        - git_version
      properties:
        name:
          description: Arbitrary name (like "everest-core")
          type: string
        version:
          description: Underlying release (like 2026.02.0)
          type: string
        git_version:
          description: Exact git revision
          type: string
